### ISSUE TITLE
Workaround for Adobe variable bug?

### ISSUE THREAD

**Issue by tiroj** [TiroTypeworks/TiroTools#13]
@khaledhosny 
InDesign still seems to have a bug that causes any adjustment of the variable slider to jump between fonts. So if the roman variable font is selected, when the slider is moved the text jumps to italic font. Is this the same [ID25 issue](https://github.com/google/fonts/issues/2391#issuecomment-642923536) that we [ran into with the STIX Two Text variable font](https://github.com/stipub/stixfonts_dev/issues/27#issuecomment-778506225)?

Is this something we can workaround in the STAT table code in the YAML config file? Or elsewhere in the build process?

**Comment by khaledhosny** [comment]
I think the work around is to set name ID 25 to a unique value in both Roman and Italic fonts. This should be possible right now by setting `names:` key on the variable font. E.g.:

```yml
fonts:
  Foo-Roman:
    source: Foo-Roman.designspace
    names:
      25: FooRoman
fonts:
  Foo-Italic:
    source: Foo-Italic.designspace
    names:
      25: FooItalic
```
