### ISSUE TITLE
Add family name suffix for variable fonts via config?

### ISSUE THREAD

**Issue by tiroj** [TiroTypeworks/TiroTools#14]
@khaledhosny 
When building variable and static fonts from a UFO+designspace path with instantiation options, can we add an option to add a name suffix to the variable font family names, e.g. " VF" (note space), so that variable and static fonts have distinct names and do no conflict in menus if both installed?

So, for example, the source MyFont.ufo + MyFont.designspace would produce a variable font with the family name `MyFont VF` (with that suffix propagating to other relevant places in the name table), while the instantiated static fonts would have family name(s) without the suffix.

I am imagining the suffix being added as a setting field in the YAML config file.

**Comment by khaledhosny** [comment]
We can do that. Or similar to https://github.com/TiroTypeworks/TiroTools/issues/13#issuecomment-1601983370, you can override the names of the variable font. It might be inconvenient, though, as one would then need to set the names for the static instances to remove the prefix. I think an explicit variable font prefix is more convenient.

**Comment by tiroj** [comment]
Have merged the pull request related to this issue. Can you document how the configuration for this works (presuming that the variable font is the first build and the static fonts are instantiated from it)?

**Comment by khaledhosny** [comment]
The suffix is added to the family nsme of the variable font name entries. This is done after the statics are instantiated, so they keep the original name.

**Comment by tiroj** [comment]
Question: Should the suffix also be applied in the name ID 25 entry?

This is being explicitly included in the config file, and currently ends up in the variable fonts exactly as stated in the YAML, but also ends up in the non-variable instantiated static fonts. I am wondering if perhaps name ID 25 should be excluded from the static font name tables, since it is variable-specific? In which case we can manually include the suffix within the ID 25 entry in the YAML.

**Comment by khaledhosny** [comment]
We can apply it to ID 25 (it does not matter where name entry comes from, when this suffix adding code kicks in, the name table if fully setup, whether the name came from the sources of from the config file). I also noticed that ID 25 remains in the static and I was meaning to look into FontTools instancer as it probably should have stripped it away.

**Comment by tiroj** [comment]
The name ID 25 entry is an oddity, because the InDesign bug means that this supposed ‘Variations PostScript Name Prefix’ applied to differentiate roman and italic variable fonts ends up actually being an arbitrary string that typically breaks normal PS naming conventions. Since it cannot be reliably derived from other name table entries, perhaps it is best to a) always treat name ID 25 as explicit in the config file (so manually include the variable suffix if used), and b) preferably strip it from the static fonts but presume it will be ignored if not.

**Comment by tiroj** [comment]
If I specify `vf-suffix: VF` at the top level in a config file, the suffix gets applied to the variable non-subset fonts, but not to subset fonts. Maybe this is a problem because the subset name table entries are explicit? e.g.
```
    subsets:
      EuphemiaLatin-Roman:
        glyphlist: source/EuphemiaLatinSubset.txt
        names:
          1: Euphemia Latin
          4: Euphemia Latin
          6: EuphemiaLatin-Regular
          25: EuphemiaLatinVF
```
Would I also need to add the vf-suffix entry at the subset level? It would be good if it were inherited in all the variable fonts.

**Comment by tiroj** [comment]
> The suffix is added to the family nsme of the variable font name entries. This is done after the statics are instantiated, so they keep the original name.

However, the VF is showing up in the PS name ID 6 and unique font identifier name ID 3 of static fonts:
<img width="893" alt="image" src="https://github.com/TiroTypeworks/TiroTools/assets/5614500/aa1bb9bf-d1fc-424e-8204-1a3b0246f45e">

**Comment by khaledhosny** [comment]
> > The suffix is added to the family nsme of the variable font name entries. This is done after the statics are instantiated, so they keep the original name.
> 
> However, the VF is showing up in the PS name ID 6 and unique font identifier name ID 3 of static fonts: <img alt="image" width="893" src="https://user-images.githubusercontent.com/5614500/248972157-aa1bb9bf-d1fc-424e-8204-1a3b0246f45e.png">

I can’t reproduce this. I’ll probably need the full config file.

**Comment by khaledhosny** [comment]
> If I specify `vf-suffix: VF` at the top level in a config file, the suffix gets applied to the variable non-subset fonts, but not to subset fonts. Maybe this is a problem because the subset name table entries are explicit? e.g.
> 
> ```
>     subsets:
>       EuphemiaLatin-Roman:
>         glyphlist: source/EuphemiaLatinSubset.txt
>         names:
>           1: Euphemia Latin
>           4: Euphemia Latin
>           6: EuphemiaLatin-Regular
>           25: EuphemiaLatinVF
> ```
> 
> Would I also need to add the vf-suffix entry at the subset level? It would be good if it were inherited in all the variable fonts.

https://github.com/TiroTypeworks/TiroTools/pull/20

**Comment by tiroj** [comment]
I am still getting this problem with the VF suffix showing up in some parts of the name table of static fonts (IDs 3 and 6). This is the complete config file [you can test this in the A23 repo @khaledhosny]

```
names:
  5: Version 3.88 

set:
  fstype: [2]
  
vf-suffix: VF

fonts:
  Euphemia-Roman:
    source: source/Euphemia-Roman.designspace
    names:
      25: EuphemiaVF
    meta:
      slng: [Latn, Cans]
      dlng: [Latn, Cans]
    instances: all
    subsets:
      EuphemiaLatin-Roman:
        glyphlist: source/EuphemiaLatinSubset.txt
        names:
          1: Euphemia Latin
          4: Euphemia Latin
          6: EuphemiaLatin-Regular
          25: EuphemiaVFLatin
        meta:
          slng: [Latn]
          dlng: [Latn]
      EuphemiaUCAS-Roman:
        glyphlist: source/EuphemiaUCASSubset.txt
        names:
          1: Euphemia UCAS
          4: Euphemia UCAS
          6: EuphemiaUCAS-Regular
          25: EuphemiaVFUCAS
        meta:
          slng: [Cans]
          dlng: [Cans]
    glyphnames: source/Euphemia.ren
    STAT:
      axes:
      - name: Weight
        tag: wght
        values:
        - name: Regular
          value: 400
          linkedValue: 700
          flags: 0x2 # ElidableAxisValueName
        - name: Book
          value: 500
        - name: Semibold
          value: 600
        - name: Bold
          value: 700
      - name: Italic
        tag: ital
        values:
        - name: Roman
          value: 0
          linkedValue: 1
          flags: 0x2 # ElidableAxisValueName
      elidedFallbackName: Regular

  Euphemia-Italic:
    source: source/Euphemia-Italic.designspace
    names:
      25: EuphemiaVFItalic
    meta:
      slng: [Latn, Cans]
      dlng: [Latn, Cans]
    instances: all
    subsets:
      EuphemiaLatin-Italic:
        glyphlist: source/EuphemiaLatinSubset.txt
        names:
          1: Euphemia Latin
          4: Euphemia Latin Italic
          6: EuphemiaLatin-Italic
          25: EuphemiaVFLatinItalic
        meta:
          slng: [Latn]
          dlng: [Latn]
      EuphemiaUCAS-Italic:
        glyphlist: source/EuphemiaUCASSubset.txt
        names:
          1: Euphemia UCAS
          4: Euphemia UCAS Italic
          6: EuphemiaUCAS-Italic
          25: EuphemiaVUCASItalic
        meta:
          slng: [Cans]
          dlng: [Cans]
    glyphnames: source/Euphemia.ren
    STAT:
      axes:
      - name: Weight
        tag: wght
        values:
        - name: Regular
          value: 400
          linkedValue: 700
          flags: 0x2 # ElidableAxisValueName
        - name: Book
          value: 500
        - name: Semibold
          value: 600
        - name: Bold
          value: 700
      - name: Italic
        tag: ital
        values:
        - name: Italic
          value: 1
      elidedFallbackName: Italic
```
