### ISSUE TITLE
meta table at the subset level?

### ISSUE THREAD

**Issue by tiroj** [TiroTypeworks/TiroTools#19]
@khaledhosny It is possible to add meta table dlng and slng data at the top level in a config file, but apparently not at the subset level. Or am I doing it wrong:

```
fonts:
  Euphemia-Roman:
    source: source/Euphemia-Roman.designspace
    names:
      25: EuphemiaVF
    meta:
      slng: [Latn, Cans]
      dlng: [Latn, Cans]
    instances: all
    subsets:
      EuphemiaLatin-Roman:
        glyphlist: source/EuphemiaLatinSubset.txt
        names:
          1: Euphemia Latin
          4: Euphemia Latin
          6: EuphemiaLatin-Regular
          25: EuphemiaVFLatin
        meta:
          slng: [Latn]
          dlng: [Latn]
      EuphemiaUCAS-Roman:
        glyphlist: source/EuphemiaUCASSubset.txt
        names:
          1: Euphemia UCAS
          4: Euphemia UCAS
          6: EuphemiaUCAS-Regular
          25: EuphemiaVFUCAS
        meta:
          slng: [Cans]
          dlng: [Cans]
    glyphnames: source/Euphemia.ren
```
