### ISSUE TITLE
Distinct feature params for different script/langsys entries?

### ISSUE THREAD

**Issue by tiroj** [TiroTypeworks/TiroTools#28]
@khaledhosny Is the support for writing feature params for ssXX and cvXX features via the YAML config file for GSUB from VOLT .input.ttf files currently able to support distinct feature params for different script and/or langsys entries? Use case would be Brill, in which e.g. Latin an Greek have different implementations for ss01 and ss02, and other ssXX features currently have only Greek implementations.

Peter C and Behdad have confirmed that this is possible within the GSUB table structure. See:
https://github.com/MicrosoftDocs/typography-issues/issues/1015#issuecomment-1763695680

I’ve not got to the build test stage of Brill updates yet, but wanted to check whether you anticipate any limitations in this area?

**Comment by khaledhosny** [comment]
No, not currently.

Currently the feature params are added to all features that match the given feature tag. We can possibly extend the syntax to allow for script and language tag, something like `ss01.latn.ENG` with both the script and language parts being optional.

**Comment by khaledhosny** [comment]
It would be a issue, though, if the same feature is referenced from different language systems but are requested to have different feature params. It would be rather complicated to try to handle this at the binary font level, so I think I’ll make it an error instead and the GSUB/GPOS table would have to be fixed before hand.

**Comment by tiroj** [comment]
Will review and test this in next few days.

_It would be a issue, though, if the same feature is referenced from different language systems but are requested to have different feature params._

To clarify, is this an issue in the new implementation, or were you able to work around it?

**Comment by khaledhosny** [comment]
> Will review and test this in next few days.
> 
> _It would be a issue, though, if the same feature is referenced from different language systems but are requested to have different feature params._
> 
> To clarify, is this an issue in the new implementation, or were you able to work around it?

The code will error for now. It feels unlikely that these two conditions are met (same feature record referenced from different language systems __and__ two different feature params are used for it), but if we catch an actual real case of this, we can figure out a fix then (it probably not that hard to split the feature record).

**Comment by khaledhosny** [comment]
Note that it is normal, even common, to have multiple feature records for the same feature tag (e.g. I can count 11 `ss01` feature records in a font I’m testing), usually each record is referenced from a different language system.

**Comment by tiroj** [comment]
I am testing this functionality for the update Brill fonts, and running into an issue this this config:

```
    featureparams:
      ss01.latn: Round capital Eng
      ss01.grek: Prosgegrammeni to ypogegrammeni
      ss02.latn: Round descending capital Eng
      ss02.grek: Variant capital Iota dialytika
      ss03.latn: Monoline grave and acute modifiers
      ss03.grek: Acraphonic forms
      ss04.latn: Insular forms
      ss04.grek: Three-bar acrophonic stater variant
      ss05: Narrow angle brackets
      ss20: Latin phonetic forms of Greek letters
      cv01:
        label: Capital Eng
        tooltip: Round and round descending capital Eng forms
        characters: [0x014A]
      cv02:
        label: Koronis editorial sign
        tooltip: Sigmoid and horizontal koronis sign forms
        characters: [0x2E0E]
      cv03:
        label: Chinnantec tone signs
        tooltip: Monoline grave and acute modifiers
        characters: [0x02CB, 0x02CA]
```
I get this error message:

`RuntimeError: Feature “ss01.latn” already has “featureparams”`

Perhaps I need to always specify a langsys as well as a script?
